// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class RegisterUserWithValidDataTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void registerUserWithValidData() {
    driver.get("https://pacific-spire-77723.herokuapp.com/");
    driver.manage().window().setSize(new Dimension(1296, 705));
    driver.findElement(By.cssSelector(".nav-item:nth-child(3) span")).click();
    driver.findElement(By.id("first-name")).click();
    vars.put("newFirstName", js.executeScript("return \"testUser\" + (Math.floor(Math.random() * 10000))"));
    System.out.println(vars.get("newFirstName").toString());
    driver.findElement(By.id("first-name")).sendKeys(vars.get("newFirstName").toString());
    driver.findElement(By.id("last-name")).sendKeys("TestUser");
    driver.findElement(By.id("pet-name")).sendKeys("TestPet");
    driver.findElement(By.id("pet-kg")).sendKeys("25");
    driver.findElement(By.id("phone")).sendKeys("0884433651");
    vars.put("newUserEmail", js.executeScript("return \"testUser\" + (Math.floor(Math.random() * 10000)) + \"@email.com\""));
    System.out.println(vars.get("newUserEmail").toString());
    driver.findElement(By.id("email_address")).sendKeys(vars.get("newUserEmail").toString());
    driver.findElement(By.id("password")).sendKeys("a123456789A#");
    driver.findElement(By.name("confirmPassword")).sendKeys("a123456789A#");
    driver.findElement(By.id("submit")).click();
    assertThat(driver.findElement(By.cssSelector("#navbarDarkProfileMenuLink > span")).getText(), is("vars.get(\"newFirstName\").toString()"));
    {
      List<WebElement> elements = driver.findElements(By.id("Search_Property"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.id("navbarDarkProfileMenuLink")).click();
    driver.findElement(By.linkText("Logout")).click();
  }
}
